name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
        source-url: https://nuget.pkg.github.com/bladepan/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
    - run: dotnet build --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release
    - name: Publish Nier.Redis
      run: dotnet nuget push Nier.Redis/bin/Release/*.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish nuget
      run: |
            for f in ./Nier.Redis/bin/Release/*.nupkg
            do
              curl -vX PUT -u "bladepan:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/bladepan/
            done
      shell: bash
